### ISSUE TITLE
I've tried jiggling the wires on this to fix the styles from behind my reverse proxy

### ISSUE THREAD

**Issue by Leopere** [DarthTigerson/Hermes#82]
Is there something special I need to do in order to make this compatible with any reverse proxies?

https://hermes.nixc.us/

**Comment by W3Edd** [comment]
Hey, if you still have this problem, maybe I can help out.
I'm on GMT - 6, for any sync purposes.
Maybe we can have chat about this over reddit? Or on discord, IDK, let me know.

**Comment by W3Edd** [comment]
I looked around.
Your instance of Hermes is running over HTTPS, aka in secure comm.
The thing here, is that the page is trying to load the CSS files over HTTP. Maybe it's hardcoded, IDK, have to dig a bit deeper.
Let me get back to you later with more information.

**Comment by W3Edd** [comment]
Hey, I found something.
Please reach out, I have some questions about how you're setting your reverse proxy.

**Comment by Leopere** [comment]
Sure where do I contact you if not here?  I think that this tool is super cool but I tried two separate standard reverse proxies to no avail. This is my deployment template currently for Hermes https://git.nixc.us/colin/hermes and the nginx.conf that is trying to make it obey https://git.nixc.us/colin/lan-to-nginx/src/branch/master/nginx.conf

**Comment by Leopere** [comment]
For future netizens if this ticket is ever useful for anyone else this is what happens.

<img width="1113" alt="image" src="https://github.com/DarthTigerson/Hermes/assets/1068374/7c115d29-4ec3-4b24-a155-ee0cb968029a">
<img width="1529" alt="image" src="https://github.com/DarthTigerson/Hermes/assets/1068374/229264c3-9a7f-4090-b083-6d750d381dea">
it works the same without browser extensions in private browsing too.

<img width="1817" alt="image" src="https://github.com/DarthTigerson/Hermes/assets/1068374/62f28165-a58e-402b-8e4e-25184ab46676">


My nginx config is

**Comment by W3Edd** [comment]
If you use Discord, add me `papayas3x10`.
